---

# Play 1
# ---------------
- name: Install mikikube and dependencies
  hosts: EC2
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: present

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Ensure Docker socket has correct group ownership
      file:
        path: /var/run/docker.sock
        owner: root
        group: docker
        mode: '0660'

    - name: Reload Docker daemon
      ansible.builtin.service:
        name: docker
        state: reloaded

    - name: Download Minikube binary
      ansible.builtin.get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Download Kubernetes GPG key
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
        dest: /tmp/Release.key
        mode: "0755"

    - name: Create directory for apt keyrings
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Convert GPG key to dearmored format
      ansible.builtin.command:
        cmd: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/Release.key
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Set permissions for Kubernetes apt keyring
      ansible.builtin.file:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        mode: '0644'

    - name: Add Kubernetes repository
      ansible.builtin.apt_repository:
        repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /'
        filename: 'kubernetes'

    - name: Set permissions for Kubernetes repository list
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/kubernetes.list
        mode: '0644'

    - name: Install kubectl
      ansible.builtin.apt:
        name: kubectl
        state: present


# play 2
# -------------
- name: Start and verify minikube is running
  hosts: EC2
  become: false

  tasks:
    - name: Start Minikube
      ansible.builtin.command: minikube start --driver=docker
      environment:
        CHANGE_MINIKUBE_NONE_USER: "true"
      register: result
      until: result.rc == 0
      retries: 2
      delay: 5
      changed_when: false

    - name: Verify Minikube status
      ansible.builtin.command: minikube status
      register: minikube_status
      changed_when: false

    - name: Print Mikinube status
      ansible.builtin.debug:
        var: minikube_status.stdout

    - name: Verify kubectl version
      ansible.builtin.command: kubectl version --client
      register: kubectl_version
      changed_when: false

    - name: Print kubectl version
      ansible.builtin.debug:
        var: kubectl_version.stdout
